
dist: trusty

branches:
  only:
  - master

language: node_js
node_js:
  - '12.16.1'

before_script:
  - npm install -g @angular/cli

cache:
  directories:
    - ./node_modules

before_script:
  - npm install -g @angular/cli

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - sed -i '/dist/d' .gitignore
  - git add . && git commit -m "latest build"

script:
  - ng lint
  - ng build --prod --base-href https://github.com/lando101/cryptolio.git


after_deploy:
  - echo "Applcation Deployed!"
