
dist: trusty
sudo: false

branches:
  only:
  - master

language: node_js
node_js:
  - '12.16.1'

addons:
  apt:
    sources:
      - google-chrome

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

