
dist: trusty
sudo: required

branches:
  only:
  - master

language: node_js
node_js:
  - '12.16.1'

before_script:
  - npm install -g @angular/cli

cache:
  directories:
    - ./node_modules

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build --prod --base-href https://github.com/lando101/cryptolio.git
